# ---------- Build stage ----------
FROM python:3.13-slim AS builder

WORKDIR /app

COPY requirements.txt .

RUN mkdir -p /root/.local && \
    pip install --no-cache-dir --user -r requirements.txt


# ---------- Runtime stage ----------
FROM python:3.13-slim

WORKDIR /app

# Copy only Docker CLI from official Docker CLI image
COPY --from=docker:cli /usr/local/bin/docker /usr/local/bin/docker

# Copy Python packages
COPY --from=builder /root/.local /root/.local

ENV PATH=/root/.local/bin:$PATH

# Copy application
COPY monitor.py .

CMD ["python", "monitor.py"]